-- CreateTable
CREATE TABLE "TRANSACAO" (
    "ID_TRANSACAO" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NOME_TRANSACAO" TEXT NOT NULL,
    "VALOR_TRANSACAO" DECIMAL NOT NULL,
    "TIPO_TRANSACAO" TEXT NOT NULL,
    "DATA_TRANSACAO" TEXT NOT NULL,
    "DESCRICAO_TRANSACAO" TEXT,
    "CATEGORIA_ID" INTEGER NOT NULL,
    CONSTRAINT "TRANSACAO_CATEGORIA_ID_fkey" FOREIGN KEY ("CATEGORIA_ID") REFERENCES "CATEGORIA" ("ID_CATEGORIA") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CATEGORIA" (
    "ID_CATEGORIA" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "DESCRICAO_CATEGORIA" TEXT NOT NULL
);
