/*
  Warnings:

  - You are about to alter the column `DATA_TRANSACAO` on the `TRANSACAO` table. The data in that column could be lost. The data in that column will be cast from `String` to `DateTime`.

*/
-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_TRANSACAO" (
    "ID_TRANSACAO" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NOME_TRANSACAO" TEXT NOT NULL,
    "VALOR_TRANSACAO" DECIMAL NOT NULL,
    "TIPO_TRANSACAO" TEXT NOT NULL,
    "DATA_TRANSACAO" DATETIME NOT NULL,
    "DESCRICAO_TRANSACAO" TEXT,
    "CATEGORIA_ID" INTEGER NOT NULL,
    CONSTRAINT "TRANSACAO_CATEGORIA_ID_fkey" FOREIGN KEY ("CATEGORIA_ID") REFERENCES "CATEGORIA" ("ID_CATEGORIA") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_TRANSACAO" ("CATEGORIA_ID", "DATA_TRANSACAO", "DESCRICAO_TRANSACAO", "ID_TRANSACAO", "NOME_TRANSACAO", "TIPO_TRANSACAO", "VALOR_TRANSACAO") SELECT "CATEGORIA_ID", "DATA_TRANSACAO", "DESCRICAO_TRANSACAO", "ID_TRANSACAO", "NOME_TRANSACAO", "TIPO_TRANSACAO", "VALOR_TRANSACAO" FROM "TRANSACAO";
DROP TABLE "TRANSACAO";
ALTER TABLE "new_TRANSACAO" RENAME TO "TRANSACAO";
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
